name: CI

on:
  pull_request:

jobs:
  test-code:
    name: code-tests
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v6
    - name: Install uv
      uses: astral-sh/setup-uv@v8.1.0
      with:
        enable-cache: true

    - name: Set up Python
      uses: actions/setup-python@v6
      with:
        python-version-file: "pyproject.toml"


    - name: Install dependencies
      run: |
        uv venv
        uv sync --locked --no-dev --group ui

    - name: Install Ruff
      uses: astral-sh/ruff-action@v4.0.0

    - name: Lint
      run: |
        ruff check --fix
        rm -rf build/
        rm -rf *.egg-info
        find . -type d -name __pycache__ -exec rm -rf {} +
        find . -type f -name "*.pyc" -delete

    - name: Test
      env:
        PLACEHOLDER_ENV_VAR: "test_placeholder"
      run: |
        uv run pytest
  
  test-build:
    name: docker-build-test
    needs : test-code
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v6
    - name: docker-build
      run: |
        docker build \
        -f Dockerfile \
        -t dockerized_model_api \
        --build-arg API_PORT="$API_PORT" \
        .